### PR TITLE
Initial Support for Mobile Client

### PR DESCRIPTION
**Pull request by DILPREET1910**
## PR Description

Initial Mobile support, to include base functionalities of the already existing desktop client as per the [mock-ups](https://github.com/foss42/apidash/issues/33#issuecomment-1605874012) suggested by @animator 

[Mobile client screen recording](https://github.com/foss42/apidash/assets/81746463/c42d721a-211c-4bed-af3c-a58d0d304cc3)

## Related Issues

- Related Issue #33 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Major ToDos
- The Request Tiles are nested under `Scrollable()` and `ReorderableListView()` widgets. Due to which scrolling and rearranging tiles works perfectly fine on desktop clients but glitches out on mobile.
- Scrolling on list of `params` and `headers` in request pane.
- Handle situation when there is no Request Tile (show `RequestEditorDefault()`) 

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, will write them after i implement the major todos
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by DILPREET1910** [comment]
Hi @animator & @ashitaprasad , please do let me know whether this navigation style would be the way forward. Please share your thoughts on the code review, according to my knowledge i have coded the current mobile layout in such a way that it doesn't interfere with the desktop clients. Let me know if you find otherwise.

if all the above changes seems fine to you I can start working on the major ToDos

**Comment by DILPREET1910** [comment]
fyi: resolved merge conflict caused by the later commits on main branch for `SendRequestButton`. Also added widget and state provider tests for bottom navbar.

**Comment by animator** [comment]
Hi @DILPREET1910 
My initial sketch was just a starting point and I would like you to think more how you can make it a much better experience for the end user. The overall App UI/UX can be improved a lot. 

Few feedback points:
- Have to scroll down to enter API endpoint.

230 ui scrolling

- The Appbar has overflow issues and no way to rename or delete request from the app bar.

230 appbar name

- For larger request body there is no way to hide the keyboard by tapping outside and access the send button. One has to scroll too much vertically to access essential components.

230 unable to hide keyboard body

- After sending a request, there is no interface that tells the user that the request is in progress and loads the response when done. We have to manually click on the response button every time.
- The theme, colors, padding of the requests in the collection pane (drawer) needs improvement. 
- Click on Settings or Home and then click on a request, it does not open the request.

**Comment by DILPREET1910** [comment]
Hey @animator.
Thanks for such an extensive feedback.

Most of these changes will be quite easy to implement.
But some of them along with the `Major Todos` mentioned in the initial message of this pull request will require major restructuring.

Considering your point
>My initial sketch was just a starting point and I would like you to think more how you can make it a much better experience for the end user. The overall App UI/UX can be improved a lot.

Moving forward I will create some mock-ups, with the view of significantly enhancing the UI/UX from the current version, incorporating your suggestions and my own ideas. Discuss them with you to finalize the basic structure of the mobile client before diving into implementation.

**Comment by DILPREET1910** [comment]
Screenshot from 2024-03-14 21-09-22
Your thoughts on removing the app drawer completely.
It seems very 2019.

Also do we have to have a home page button on the mobile client?

**Comment by DILPREET1910** [comment]
Hi @animator @ashitaprasad 
Would love to have your thoughts on this.

1. Removing the app drawer, having collection pane as shown in the image.
Screenshot from 2024-03-14 21-09-22
2. Navigator pushing request,response,code panes for each tile in the collection pane
Screenshot from 2024-03-16 10-11-32
3. Removing the navigation bar from the earlier mockups.
4. Having an infinite scroll instead for request, response, code panes.
Android Large - 3
5. For too many url and header params, we can have a widget that shows only the preview up to specified height and then expands once clicked. 
Android Large - 4

**Pull request closed without merging**
