### PR TITLE
fixes Sync url and params tab issue

### LINKED ISSUE #166: Sync url and params tab
**Describe the bug/problem**
Syncing of url and params tab

**Steps to Reproduce the bug/problem**
1. After opening the app, paste `https://api.foss42.com/country/data?code=US` in the url field
Screenshot 2024-02-23 at 7 05 41 PM

**Expected behavior**
1. If we paste a url which has parameters in it, it should be synced with params tab
Screenshot 2024-02-23 at 7 06 35 PM
2. If we add params in the params tab, they should get added in the url.

**Device Info (The device where you encountered this issue):**
 - OS: MacOS
 - Version: Sonoma 14.3.1

### PR DESCRIPTION
**Pull request by amankumarmahavar**
## PR Description

This pull request enables the synchronization of the URL with URL parameters and vice versa

https://github.com/foss42/apidash/assets/72187898/17497404-c384-4f3c-87a7-53968bed227a

## Related Issues

- Related Issue #166
- Closes #166

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [ ] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_
- [x] I need help with writing tests

### CODE REVIEW

**Comment by opxdelwin** [comment]
Hey, quick question, does it go the other way around? i.e, If a URL with query params are pasted/typed directly into the `URLField`, does the params tab update as per?

**Comment by amankumarmahavar** [comment]
Yes its working 

https://github.com/foss42/apidash/assets/72187898/b0634cf8-357e-4ea3-b42b-5e1c9efc94f6

**Comment by opxdelwin** [comment]
I see few commented lines making it into the PR, it'd be easier for maintainers if you could remove em' beforehand. The approach looks solid! 🚀

**Comment by amankumarmahavar** [comment]
Surely will consider the remark...

**Comment by ashitaprasad** [comment]
Refer https://github.com/foss42/apidash/issues/166#issuecomment-1994440372

**Pull request closed without merging**
