### PR TITLE
[feat] Add Spanish and French l10n

### LINKED ISSUE #273: [feat] Implement Spanish and French Language Support
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add Spanish and French language support to enhance accessibility and usability.

**Expected Outcome:**
Enhanced accessibility and wider user reach.

**Additional Information:**
Aligns with inclusivity goal and expands user base.

**Implementation**

1. Add language files for Spanish (app_es.arb) and French (app_fr.arb).
2. Integrate `flutter_localizations` package for seamless language switching.
3. Implement language selection feature in settings.
4. Ensure dynamic localization without app restart.

### PR DESCRIPTION
**Pull request by opxdelwin**
## PR Description

This PR introduces a new feature to APIDash, allowing users to switch between English, Spanish, and French languages for the interface. Users can now select their preferred language and save it as their default setting in the settings page.

By default English has been set to fallback language.

Used Google translate for translation, did verify the reverse to get an accurate translation. Will prefer a native speaker's confirmation over the top as well.

## Related Issues

- Related Issue #273 
- Closes #273 

### Checklist
 - [ ] Reverse translate to verify integrity of sentences.
 - [x] Add l10n dependency for tests
 - [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
 - [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [x] No, and this is why: Not sure if l10n needs tests. Will add if required.

### CODE REVIEW

**Comment by opxdelwin** [comment]
I've updated major parts of the UI, just fixed old tests and added localization for all `MaterialApp`s within them. I have like 4 tests failing on my machine, probably due to my copy of Flutter, please do verify accordingly.

If there's any part of UI that I've missed on translation, do let me know. There seems to be one or so in `ResponsePane` side of things, please do have a look :)

Awaiting initial feedback.

**Comment by animator** [comment]
Hi @opxdelwin Kindly raise an issue and link this PR to it.
Thanks.

**Comment by animator** [comment]
@opxdelwin The english strings should have been as it is .. why have you modified them without informing us or mentioning in this PR?
Few Examples:
- kLabelAddKey: " Add Key" -> "Add Key"
- kLabelAddValue: " Add Value" -> "Add Value"
- kLabelAPIHeaderName: "Add Header Name" -> "Header Name"
- kLabelAPIHeaderValue: “ Add Header Value" -> "Header Value"
- kLabelAddURLParameters: "Add URL Parameter" -> "Add Parameters"

& many more

**Comment by opxdelwin** [comment]
Thanks for pointing this out, my apologies for the overlook, I've been engaged for a while hence didn't get time to comprehensively recheck. I'll ping you once done. 
Along with this, in translations, few of them have been affected in a similar way such as 
 - home -> House (spanish) ; changed to "home page" in PR to get appropriate translation. 

what changes should I do to these?

**Comment by animator** [comment]
Closing this PR as this feature will require a bit more structure, pre-planning & native language speakers for implementation.

**Pull request closed without merging**
