### PR TITLE
fix: testcases and dart dio codegen

### LINKED ISSUE #283: Fix Dart (dio) codegen & tests
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

dio package API has been updated which is breaking the existing generated codes. 
The task is to update the current Dart (dio) codegen, verify the generated codes and update the test file (don't forget to add new test cases for multipart POST 4-9).

To learn more about codegens check out #80 

See example test script for [Python (requests)](https://github.com/foss42/apidash/blob/main/test/codegen/python_requests_codegen_test.dart) which covers all the test cases.

### PR DESCRIPTION
**Pull request by nikkivirtuoso**
## PR Description

as the dio package has been updated I have fixed the code according to the package and included the testcases POST4-9

## Related Issues

- Related Issue #283 
- Closes #283 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by nikkivirtuoso** [comment]
@ashitaprasad please have a look, I have modified the code for dart dio i will update all the test cases once you approve the modified code

**Comment by animator** [comment]
@nikkivirtuoso The point of having test cases is to help us in reviewing the code. Please update all the test cases and let us know.

**Comment by nikkivirtuoso** [comment]
@animator @ashitaprasad i have updated all the test cases please have a look

**Comment by nikkivirtuoso** [comment]
@ashitaprasad ma'am I have configured my email, now please have a look to my PR

**Comment by ashitaprasad** [comment]
@nikkivirtuoso Have you run all the generated code samples in the test file individually on your local machine and checked if they are running ?

**Comment by nikkivirtuoso** [comment]
yes ma'am

**Comment by ashitaprasad** [comment]
@nikkivirtuoso The generated code for cases POST 4 to POST 9 have syntax errors and do not compile. Can you please make sure that the generated code compiles properly and can be executed to give the results.

**Comment by nikkivirtuoso** [comment]
@ashitaprasad ma'am now it is compiling and i have updated the test cases POST 4 to POST 9 accordingly

**Comment by ashitaprasad** [comment]
LGTM 🚀

**Pull request merged**
