### PR TITLE
Validate JAVA Http Client Codegen and add relevant testcases

### LINKED ISSUE #137: Validate Java (HTTP Client) CodeGen & add all test cases
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Java
Library - https://openjdk.org/groups/net/httpclient/intro.html

More info here - #80

### PR DESCRIPTION
**Pull request by apoorvdwi**
## PR Description

This PR fixes the Java http client codegen and adds the relevant tests.

## Related Issues

- Related Issue #137
- Closes #137

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes

### Steps to run
Java code is relatively hard to run on local machine due to install overheads which is why I prepared a simple dockerfile given below

```dockerfile
# Use the official OpenJDK image for a base image
FROM openjdk:23

# Set the working directory inside the container
WORKDIR /usr/src/myapp

# Copy the Main.java file from the local directory to the container's working directory
COPY Main.java /usr/src/myapp/
COPY 1.png /usr/src/myapp/

# Include Gson JAR file (assuming it is available locally)
COPY gson-2.8.9.jar /usr/src/myapp/

# Add Gson JAR file to the classpath
ENV CLASSPATH=.:/usr/src/myapp/gson-2.8.9.jar

# Compile the Java program
RUN javac Main.java

# Run the Java program when the container launches
CMD ["java", "Main"]
```

- Put this in a folder with a file called Main.java and paste the code you want to run in the file
- Download the gson jar file from [here](https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar) and put it in the same folder
- Put any image in the same folder as well and either rename it to `1.png` or change in the dockerfile and image can be used in formdata with path `/usr/src/myapp/<filename>`
- execute the below command
```sh
docker build -t java-app . && docker run --rm java-app
```

### CODE REVIEW

**Comment by apoorvdwi** [comment]
@ashitaprasad @animator please review this PR
Let me know if you face any difficulties in running the code

I'm pasting a few screenshots of code runs just in case

Screenshot 2024-03-23 at 9 42 34 PM
Screenshot 2024-03-23 at 9 43 16 PM

**Comment by animator** [comment]
POST 2 & POST 3 generated code is giving incorrect output.
```
Response body: {"detail":[{"type":"model_attributes_type","loc":["body"],"msg":"Input should be a valid dictionary or object to extract fields from","input":"{\n\"text\": \"I LOVE Flutter\"\n}","url":"https://errors.pydantic.dev/2.6/v/model_attributes_type"}]}
Response code: 422
```

Expected Output:
```
Response body: {"data":"i love flutter"}
Response code: 200
```

**Comment by animator** [comment]
Also HEAD2 is
```
codeGen.getCode(
              CodegenLanguage.javaHttpClient, requestModelHead2, "http"),
          expectedCode);
```
instead of
```
codeGen.getCode(
              CodegenLanguage.javaHttpClient, requestModelHead2, "https"),
          expectedCode);
```

**Comment by apoorvdwi** [comment]
@animator fixed the head2 testcase and json body type parsing

**Comment by animator** [comment]
Thanks for the PR. LGTM 🚀

**Pull request merged**
