### PR TITLE
Add MQTT Support

### PR DESCRIPTION
**Pull request by mmjsmohit**
## PR Description

This PR adds support for MQTT v3 (3.1 and 3.1.1) Client Testing using the [mqtt_client](https://pub.dev/packages/mqtt_client) package.

1. The foundation of our MQTT service has been expanded with the addition of new models.
2. A working version of our MQTT service has been successfully implemented.
3. I've added support for MQTT topic subscriptions, allowing users to subscribe to multiple topics at once.
4. Some level of error handling has been taken care of. I plan to make a separate PR for writing and fixing tests and implementing comprehensive level of error handling.

## Related Issues

- Related Issue #115 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [ ] I have run the tests (`flutter test`) and all tests are passing.
> Some tests are failing, I plan to make a separate PR for fixing and writing more tests.

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [x] No, and this is why: _I plan to make a separate PR for adding tests._

### CODE REVIEW

**Comment by mmjsmohit** [comment]
@ashitaprasad @animator Would love to receive your inputs on the current implementation!

> Go API Dash! 🫶🏻

**Comment by khanjasir90** [comment]
@mmjsmohit can we use json_serializable for to and from json code generation and equatable for ==.
@ashitaprasad what's your take on this.

**Comment by mmjsmohit** [comment]
> @mmjsmohit can we use json_serializable for to and from json code generation and equatable for ==. @ashitaprasad what's your take on this.

Sure! That's a good suggestion @khanjasir90 considering the model classes are fairly complex. Currently, I am busy with my mid-terms. Will add that soon.

**Comment by animator** [comment]
@mmjsmohit Please make this change  https://github.com/foss42/apidash/issues/307

**Comment by mmjsmohit** [comment]
Required changes made! 


https://github.com/foss42/apidash/assets/65406090/00488c8c-69e4-40bb-94d9-a38793a87201

**Comment by ashitaprasad** [comment]
@mmjsmohit Can you resolve the conflicts for this PR.
Some feedback on the existing implementation :
State management of the values being entered is not correct. When the user switches screens, the values disappear. 


https://github.com/foss42/apidash/assets/1382619/d924769d-742b-4187-89a0-2d8d073794c0



And change the color of the switch from purple. Keep it in accordance with the theme of API Dash

**Comment by mmjsmohit** [comment]
Hi @ashitaprasad,

I’ve resolved the conflicts in the PR and also migrated to DataTable2 from DaviTable. Additionally, I’ve made several UI fixes. You can find more details in the video and screenshots below:

### Light Mode:
Screenshot from 2024-04-05 16-05-43
### Dark Mode:
Screenshot from 2024-04-05 16-02-46
### Video:
[Screencast from 2024-04-05 16-15-58.webm](https://github.com/foss42/apidash/assets/65406090/4a4a4ce9-e535-40bf-bad1-fa305e39fca1)

**Comment by ashitaprasad** [comment]
@mmjsmohit There is an issue in the implementation. Every time, I create a new MQTT request, automatically the response and request fields of the previous MQTT request gets filled. This should not happen.

**Comment by mmjsmohit** [comment]
I am currently enhancing the handling of MQTT requests to ensure robustness. Should I create a new model specifically for MQTT, or would it be better to modify the existing request model?

**Comment by ashitaprasad** [comment]
@mmjsmohit It should be a new model.

**Comment by ashitaprasad** [comment]
Closing this PR as request model has now been updated.

**Comment by badnikhil** [comment]
@ashitaprasad  Can i work ahead on this PR or start things from scratch using similar approach?

**Comment by animator** [comment]
@badnikhil better to start things from scratch as the code base has evolved.

**Comment by badnikhil** [comment]
> @badnikhil better to start things from scratch as the code base has evolved.



> @badnikhil better to start things from scratch as the code base has evolved.

work in progress.. just a doubt... Still there should be  new model or modify the current http res/req models?

**Comment by badnikhil** [comment]
the project in my 2nd proposal includes adding mqtt and grpc support. Is it fine if I implement that now? Or I should pick a different issue.

**Pull request closed without merging**
