### PR TITLE
Add CodeGen for Go (http)

### LINKED ISSUE #130: Add CodeGen for Go (http)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add code generator for Go 
Library - https://pkg.go.dev/net/http

### PR DESCRIPTION
**Pull request by apoorvdwi**
## PR Description

Added CodeGen for Golang HTTP

## Related Issues

- Related Issue #130 
- Closes #130 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
Added relevant tests for go code generator

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by apoorvdwi** [comment]
@ashitaprasad @animator Please review this 😄

**Comment by animator** [comment]
@apoorvdwi Can you kindly update the test cases to include example Request Models POST 4 to POST 9 which have been recently added.

**Comment by apoorvdwi** [comment]
Hey @animator, all 27 test cases are already there in the test file.
I have resolved conflicts to accommodate changes done in refactoring codegen.

**Comment by apoorvdwi** [comment]
Got it, thanks
Will make sure to follow these fixes in upcoming PRs

**Pull request merged**
