### PR TITLE
CodeGen for R (httr) added

### LINKED ISSUE #145: Add CodeGen for R (httr)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for R
Library - https://github.com/r-lib/httr

Follow the instructions provided [here](https://github.com/foss42/apidash/discussions/80)

### PR DESCRIPTION
**Pull request by ayush-mahawar26**
## PR Description

Adding codegen for R using httr.

## Related Issues

- Related Issue #145 
- Closes #145 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

Screenshot 2024-07-27 005558

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No

# Instructions to run the generated code in local computer
## In RStudio
- Install R
- Install the packages `foreach` and `doParallel`
- Copy the script from the ApiDash CodeGen
- Run the script.

## Using Docker
- Create a local directory called `r-test-flutter`.
- run the following command  - 
   `cd r-test-flutter` - to change the directory r-test-flutter.
  `code .` - to open the folder in VS Code.
- Install [Docker](https://www.docker.com/)
- Inside `r-test-flutter` create a `DockerFile` .
- Replace in DockerFile with [DockerFileContent.txt](https://github.com/user-attachments/files/16396165/DockerFileContent.txt)
- create `script.r` and paste the copied code from CodeGen of ApiDash `R (httr)`.
- to run the R code from Docker -
   `docker build -t my_r_script . ` - this will build your image of R inside the Docker.
  `docker run -t --rm my_r_script ` - this will run your R file.
- In console you will get your Api Response.

### CODE REVIEW

**Comment by ashitaprasad** [comment]
You also need to follow the instructions provided [here](https://github.com/foss42/apidash/discussions/80) for adding a new codegen

**Comment by ayush-mahawar26** [comment]
sorry for inconvenience, this is my first time in open source.
according to [this](https://github.com/foss42/apidash/discussions/80), can you please clarify , I just only need to add the test in `test/codegen/` for the code Gen so that all the case in `test/request_model.dart` should be pass.

**Comment by ashitaprasad** [comment]
@ayush-mahawar26 the tests should not just pass. But, the generated codes should also work locally in your PC. 
Also, you need to post the installation instructions to run the code locally in this PR.

**Comment by ashitaprasad** [comment]
POST 4 code fails on execution. All submitted test cases should run locally and in this case it was not done. Please follow guidelines. 
POST 6 to 10 test cases are missing.
The multipart formdata code does not follow the httr reference located here https://httr.r-lib.org/index.html

**Pull request closed without merging**
