### PR TITLE
added test cases for kotli okhttp3

### LINKED ISSUE #280: Verify kotlin (okhttp) codegen & Update test scripts
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

New example requests have been added - **POST 4 to POST 9** in [test/request_models.dart](https://github.com/foss42/apidash/blob/main/test/request_models.dart) which tests multipart formdata functionality of the codegens. These request models need to be included in the test script for **kotlin (okhttp)** codegen. And the result generated must be verified by running it locally before adding it to the test file as the expected code. 

See example test script for [Python (requests)](https://github.com/foss42/apidash/blob/main/test/codegen/python_requests_codegen_test.dart) which covers all the test cases.

To learn more about codegens check out #80

### PR DESCRIPTION
**Pull request by PCoder23**
## PR Description

Added test codes for post 4 and post 6 to 9, as post 5 already written (also manually checked the codes for non-image ones , and it was working fine)
## Related Issues

- Closes #280 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by animator** [comment]
Have you run the generated code of these test cases locally in your computer and verified that all of them are working.

**Comment by PCoder23** [comment]
ran the non file ones and it was working fine

Screenshot 2024-03-15 181348

 but the file ones are showing error , sending you a pr soon after correcting the codegen

**Comment by animator** [comment]
Also run the file ones by replacing the dummy path with a path to a local image file.

**Comment by animator** [comment]
Yes @PCoder23

**Comment by PCoder23** [comment]
now working fine for file ones too 

Screenshot 2024-03-15 224256

Please review @animator

**Comment by animator** [comment]
LGTM 👏

**Pull request merged**
