### PR TITLE
Feat(tests):  add unit test pipelines

### PR DESCRIPTION
**Pull request by sebastianbuechler**
## PR Description

This PR adds a set of pipelines that run all unit tests and flutter analyzer. It uses matrix strategy to run on all three supporter operating systems and two flutter versions (currently 3.16.9 and latest 3.x version). 

Currently, on windows there's one test failing because of windows specific implementation.

Additionally, I had to clean up some stuff for the flutter analyzer to succeed:
- remove unused variables (maybe the entire code on those changes can be removed?)
- remove generated files for `analysis_options.yml` file so that they are not scanned
- add a super call where it was needed
- remove unused imports

## Related Issues

- Related Issue #219 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing -> almost all tests as described above and this is the intention of this PR

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by animator** [comment]
Currently, we are not accepting any workflows.
Apart from the changes you made in the two files `analysis_options.yaml` &`lib/widgets/json_previewer.dart`, you can revert all other changes and update this PR which can be merged.

**Comment by sebastianbuechler** [comment]
@ashitaprasad Is there a specific reason why such a basic pipeline needs approval to run or can this be adjusted?

**Comment by sebastianbuechler** [comment]
> Currently, we are not accepting any workflows.
> Apart from the changes you made in the two files `analysis_options.yaml` &`lib/widgets/json_previewer.dart`, you can revert all other changes and update this PR which can be merged.
> 

Why no pipelines? It already catched a bug on windows and shows some code smells in the existing project. Given the huge number of open PRs a testing pipeline is highly beneficial.

**Comment by animator** [comment]
Closing the PR as we are not currently accepting any workflow.

**Pull request closed without merging**
