### PR TITLE
Add response previewer for text/html

### PR DESCRIPTION
**Pull request by monstajoe2002**
## PR Description

_Add your description_

## Related Issues

- Related Issue #155 
- Closes #165

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [ ] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_
- [x] I need help with writing tests

### CODE REVIEW

**Comment by BrawlerXull** [comment]
Hey 👋  the packages used in the pr 
- `webview_cef: ^0.1.0`
- `webview_flutter: ^4.7.0`

None of them supports `Linux`

I suggest using `desktop_webview_window` as it supports all the 3 platforms - `MacOs , Windows and Linux`

**Comment by mmjsmohit** [comment]
@BrawlerXull The package `desktop_webview_window` has some pre-requisites which are necessary to be installed on the user's machine. We would have to figure out how to install the pre-reqs while API Dash is being installed.

See https://pub.dev/packages/desktop_webview_window#linux-requirement

**Comment by monstajoe2002** [comment]
> @BrawlerXull The package `desktop_webview_window` has some pre-requisites which are necessary to be installed on the user's machine. We would have to figure out how to install the pre-reqs while API Dash is being installed.
> 
> See https://pub.dev/packages/desktop_webview_window#linux-requirement

Exactly, this approach also spawns a new webview window, which is not the desired outcome as per the screenshot in the original PR.

**Comment by monstajoe2002** [comment]
Shall I close this request or is someone gonna merge it?

**Comment by animator** [comment]
@monstajoe2002 It takes time to review and merge PRs. Please be patient.

**Comment by mmjsmohit** [comment]
Hi @monstajoe2002!
I am getting the following error when running your code:

```
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:webview_cef/src/webview.dart': Failed assertion: line 197 pos 12: 'value': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      WebViewController._cursorMove (package:webview_cef/src/webview.dart:197:12)
#3      WebViewState._buildInner.<anonymous closure> (package:webview_cef/src/webview.dart:310:25)
#4      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3084:30)
#5      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
#7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#11     _invoke1 (dart:ui/hooks.dart:328:13)
#12     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#13     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
```
I am running API Dash on Ubuntu 23.10.

**Comment by monstajoe2002** [comment]
I haven't tested it on Linux. However, I would encourage you to try this fix: https://github.com/hlwhl/webview_cef#linux-

**Comment by monstajoe2002** [comment]
I found `webview_universal`, which should supposedly work on Linux. However, it creates a separate window for that HTML page. Is that OK for you?

**Comment by animator** [comment]
@monstajoe2002 Please add preview (screenshot) for the test case given [here](https://github.com/foss42/apidash/issues/155#issuecomment-1962190036)

**Comment by monstajoe2002** [comment]
image
Here's the result after using `webview_universal`

**Comment by animator** [comment]
@monstajoe2002 Ahh it opens in a new window. This won't work as it will lead to poor user experience.

**Comment by animator** [comment]
@monstajoe2002 If a solution works for macOS & Windows and does not work for Linux, it is acceptable. We can raise an improvement issue to add support for Linux for that feature so that the community can work on it and add it when it is available..

**Comment by monstajoe2002** [comment]
Exactly. Do note that I had to modify `main.cpp` (Desktop binary) in the `windows` directory on Windows to get it working according to the [webview_cef](https://pub.dev/packages/webview_cef) documenation. This is ignored by git by default.

**Comment by animator** [comment]
One issue with [webview_cef](https://pub.dev/packages/webview_cef) is that the build size will increase drastically due to chromium binary. Is there any other alternative?

**Comment by monstajoe2002** [comment]
So far, no. How drastic are we talking?

**Comment by monstajoe2002** [comment]
Why did you close #165?

**Comment by animator** [comment]
> So far, no. How drastic are we talking?

Adding ~200 MB just to add this feature is an overkill. The current size is ~30 MB.

> Why did you close #165?

As the package used did not provide the desired result.

**Pull request closed without merging**
