### PR TITLE
feat: automatic row adding, handling checkbox selection when empty

### LINKED ISSUE #304: Relocate/Remove "+ Add Header", "+ Add Param" & "+ Add Form Data" Buttons
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
First discussed in #58 

"+ Add Header", "+ Add Param" & "+ Add Form Data" buttons require users to go down to the screen, which at times is inconvenient. These buttons can be relocated to a more accessible position like above the parameter fields.

It would also be a much better UX if a new empty row is automatically added below the last row if the user enters something in the last row. In this case the buttons can be eliminated.

### PR DESCRIPTION
**Pull request by DenserMeerkat**
## PR Description

>**_Chose to merge fixes for issues #304 and #309 into a single PR to avoid potential conflicts during merging as they required modifying the same file._**

Rows now get added automatically when user enters anything in the last row, accordingly removed the Add Param/Header/Form Data buttons.

Mimicked the Postman's behaviour of adding rows automatically and of checking and unchecking rows.
Postman hides the Checkbox if a field isn't touched yet, but I decided to keep it and have it disabled since hiding it didn't look good. Expecting feedback on this.

## Related Issues

- Related Issue #304 
#309 
- Closes #304 
#309
### Checklist
- [X] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [X] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [X] No, and this is why: I Don't believe it requires/breaks any tests, will update if asked to.

### CODE REVIEW

**Comment by animator** [comment]
@DenserMeerkat Check out the case below for which it is breaking. Add params/headers -> save -> close -> reopen -> no empty row at the bottom.

https://github.com/foss42/apidash/assets/615622/e18f3a48-8043-45f9-8545-7a35d535735a

Also, after further pondering we think it is better to retain the buttons in the bottom for a while until this approach works perfectly in the wild.

**Comment by DenserMeerkat** [comment]
>Check out the case below for which it is breaking. Add params/headers -> save -> close -> reopen -> no empty row at the bottom.

Will look into it.

>Also, after further pondering we think it is better to retain the buttons in the bottom for a while until this approach works perfectly in the wild.

Right, understandable.

**Comment by animator** [comment]
@DenserMeerkat Just a clarification in case the previous comment caused any confusion ... 
We want to include the features in this PR + retain the buttons as well.

**Comment by DenserMeerkat** [comment]
> @DenserMeerkat Just a clarification in case the previous comment caused any confusion ... We want to include the features in this PR + retain the buttons as well.

Oh gotcha, will add them back.

**Comment by ashitaprasad** [comment]
@DenserMeerkat Is the PR ready for review ?

**Comment by DenserMeerkat** [comment]
Not yet @ashitaprasad,
I'm still working on the breaking case @animator pointed out.

[#300](https://github.com/foss42/apidash/pull/300) is ready though.

**Comment by ashitaprasad** [comment]
Sure 👍

**Comment by DenserMeerkat** [comment]
The PR is now ready for review @ashitaprasad.
The empty row now shows up when there are already existing rows in a request.

**Comment by animator** [comment]
LGTM 🚀

**Pull request merged**
