### PR TITLE
Add double click to maximise/unmaximise on windows #193

### LINKED ISSUE #193: Double click to maximise/minimise on windows
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Native windows apps usually have a "double click to maximise/unmaximise the window" feature.

**Describe the solution/feature you'd like us to add**
Double click to maximise/unmaximise.

### PR DESCRIPTION
**Pull request by zeeshanok**
Fixes #193

### CODE REVIEW

**Comment by ashitaprasad** [comment]
This feature currently works only on Windows. Usually this feature is available on all Desktop platforms including Linux and MacOS. Can you make the required modifications to the PR and make sure it supports all platforms.

**Comment by zeeshanok** [comment]
While I can definitely implement those changes, I don't have a Linux or Mac machine to test it on.

**Comment by ashitaprasad** [comment]
@zeeshanok You can spin up a Linux distro on VM.

**Comment by ashitaprasad** [comment]
@BrawlerXull , you can send across a PR.

**Comment by ashitaprasad** [comment]
@BrawlerXull The implementation is incorrect hence your PR has been closed. Please read the closing comments on the PR for further details.

**Comment by zeeshanok** [comment]
> @zeeshanok You can spin up a Linux distro on VM.

@ashitaprasad I ran apidash on a Linux VM and it looks like the app's titlebar is the native one (which already supports double-click). Should I write it so that the custom titlebar is also on Linux and Mac?

**Comment by animator** [comment]
@zeeshanok will review and get back to you.

**Comment by animator** [comment]
Adding `onDoubleTap` to `GestureDetector` is not the correct approach so closing this PR.
Please open a new PR in case you come up with a better approach.

**Pull request closed without merging**
