### PR TITLE
Added form-data and contentType from the Curl parser that got updated

### LINKED ISSUE #506: form-data and contentType from the Curl parser
#### Tell us about the task you want to perform and are unable to do so because the feature is not available
Importing form-data through curls not working.

#### Describe the solution/feature you'd like us to add
The curl parsing library is already parsing the form data we just need to pass them to HTTPRequest model

### PR DESCRIPTION
**Pull request by WrathOP**
## PR Description

Now storing the form-data in the httpRequestModel too.

Just tell me if you want to alter/remove the logic for content-type.

## Related Issues

- Closes #506 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I am using the latest Flutter stable branch (run `flutter upgrade` and verify)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [x] No, and this is why: Just passing on the already tested code's variable to the model.

## OS on which you have developed and tested the feature?

- [ ] Windows
- [x] macOS
- [ ] Linux

### CODE REVIEW

**Comment by ashitaprasad** [comment]
Open an issue and link this PR.

**Comment by ashitaprasad** [comment]
Kindly add tests verifying given a curl string correct HttpRequestModel is being obtained.

**Comment by WrathOP** [comment]
Sorry for the delays was busy, added the tests you asked for.

**Comment by ashitaprasad** [comment]
Thanks for the PR @WrathOP 🚀
Now that you are a curl-master, definitely looking forward to you attacking Hurl! ( https://github.com/foss42/apidash/issues/123)

**Comment by WrathOP** [comment]
> Thanks for the PR @WrathOP 🚀
> 
> Now that you are a curl-master, definitely looking forward to you attacking Hurl! ( https://github.com/foss42/apidash/issues/123)
> 
> 

Sure will work in it, heard about HURL for first time though

**Pull request merged**
