### PR TITLE
Added PHP httpPlug Codegen

### LINKED ISSUE #144: Add CodeGen for PHP (HTTPlug)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for PHP
Library - https://github.com/php-http/httplug

### PR DESCRIPTION
**Pull request by apoorvdwi**
## PR Description

This PR adds codegen for PHP httpPlug

## Related Issues

- Related Issue #144
- Closes #144

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes

### Steps to run
I prepared a simple dockerfile that eases the running of PHP code given below

```dockerfile
# Use the official PHP image with Apache
FROM php:7.4-apache

# Install git and unzip which might be needed for composer operations
RUN apt-get update && apt-get install -y git unzip

# Install Composer globally
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');"

# Set the working directory to the root of your Apache directory
WORKDIR /var/www/html

# Copy your PHP script to the Docker image
COPY . /var/www/html/

# Use Composer to install dependencies
RUN composer install

# Expose port 80 to access the Apache server
EXPOSE 80

# Start Apache in the foreground
CMD ["apache2-foreground"]
```

- Put this in a folder with a file called script.php and paste the code you want to run in the file
- Create a `composer.json` file in the same folder with below content
```json
{
  "require": {
    "php-http/discovery": "^1.14",
    "php-http/guzzle7-adapter": "^1.0",
    "guzzlehttp/psr7": "^2.0",
    "nyholm/psr7": "^1.4",
    "nyholm/psr7-server": "^1.0"
  }
}
```
- Put any image in the same folder as well and image can be used in formdata with path `./<filename>`
- execute the below command
```sh
docker build -t php-apache-app . && docker run --rm -p 80:80 php-apache-app
```
- Once the dockerfile is up and running, browse to `http://localhost/script.php` or run the below curl in separate in terminal to see the output
```sh
curl http://localhost/script.php
```

### CODE REVIEW

**Comment by apoorvdwi** [comment]
@ashitaprasad @animator please review this PR
Let me know if you face any difficulties in running the code

Here is a screenshot of the code runs just in case
Screenshot 2024-04-06 at 2 12 20 PM

**Comment by animator** [comment]
Multipart implementation is bloated and can be heavily simplified.
Take a look at https://docs.php-http.org/en/latest/components/multipart-stream-builder.html

**Comment by apoorvdwi** [comment]
- Made the changes
- Verified the newly generated code
- Updated the tests

@animator let me know if any more changes are required

**Comment by animator** [comment]
Why are you hardcoding boundary?
MultipartStreamBuilder already add a boundary that can be obtained using
```
$boundary = $builder->getBoundary();
```
https://docs.php-http.org/en/latest/components/multipart-stream-builder.html#building-a-multipart-stream

**Comment by apoorvdwi** [comment]
Yes, we can use that as well or we can pass a custom boundary as well. I was using the later way.
I have made the changes to use default boundary from multiparts builder

**Comment by animator** [comment]
Thanks for fixing the issue. LGTM 🚀

**Pull request merged**
