### PR TITLE
Add code generation for C

### LINKED ISSUE #138: Add CodeGen for C (Libcurl)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for C
Library - libcurl

### PR DESCRIPTION
**Pull request by mohnishdeshpande**
## PR Description

Add code generation for C programming language using the libcurl library.

## Related Issues

- Closes #138 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
- [x] Yes
- [ ] No, and this is why: 
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by animator** [comment]
You need to add tests where the expected codes generated have been manually run and verified in your computer. All are codegen test cases are golden tests which have been manually verified.

**Comment by mohnishdeshpande** [comment]
@animator Sure thing.

**Comment by mohnishdeshpande** [comment]
@animator Please have a look I have added the tests. All tests pass and I have manually verified them.

**Comment by animator** [comment]
@mohnishdeshpande Can you kindly update the test cases to include example Request Models POST 4 to POST 9 which have been recently added.

**Comment by mohnishdeshpande** [comment]
@animator Sure. However, it's a little tricky for me. Since the creation of the PR, the repo was updated, which now causes merge conflicts. Do you have any workflow suggestion to update a out of sync feature branch when there are merge conflicts. Also, for some reason the merge editor on web is greyed out. 

image

**Comment by animator** [comment]
@mohnishdeshpande as your changes are only a few files, I recommend you to close this PR. Create a new branch from main .. make changes & open a new PR.

**Comment by animator** [comment]
In the new PR also include instructions on how one can run the generated code.

**Comment by mohnishdeshpande** [comment]
@animator Copy that. Currently, the generated code shows the command to compile and run the generated code. Are you hinting at any other instructions?

**Comment by animator** [comment]
That is not required .. Please remove it from the generated code and include the instructions in the PR comment.

**Pull request closed without merging**
