### PR TITLE
Adding: C language using curl library

### LINKED ISSUE #138: Add CodeGen for C (Libcurl)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for C
Library - libcurl

### PR DESCRIPTION
**Pull request by nikkivirtuoso**
## PR Description

this PR has C libcurl codegen correct code

## Related Issues

- Related Issue #138 
- Closes #138

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by nikkivirtuoso** [comment]
### Step 1: 
You can install libcurl using Homebrew, a popular package manager for macOS. Open Terminal and run the following command:
``` brew install curl ```

### Step 2: 
Write your C code using libcurl. You can use any text editor or an integrated development environment (IDE) like Xcode or Visual Studio Code.

### Step 3: 
Assuming you have a C file named main.c containing your libcurl code, you can compile it using `gcc` . Open Terminal and navigate to the directory containing your C file.
``` cd /path/to/your/project```
``` gcc -o my_program main.c -lcurl ```

This command compiles your `main.c` file and links it with the libcurl library (`-lcurl`). The resulting executable will be named `my_program.`

### Step 4:
Once compiled successfully, you can run your program from the Terminal:
``` ./my_program ```

**Comment by nikkivirtuoso** [comment]
@ashitaprasad @animator  the above steps can be used to run the program

**Comment by ashitaprasad** [comment]
There are compilation errors in the generated code, like for cases GET5 and GET6. 
Please fix them.

**Comment by nikkivirtuoso** [comment]
@ashitaprasad @animator done with the compilation error please have a look

**Comment by ashitaprasad** [comment]
@nikkivirtuoso Why are headers being added in the generated code even when no headers are being sent.

Take the example of GET1
`struct curl_slist *headers = NULL;`
`
curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
`
Is this required in the GET1 example ?

**Comment by nikkivirtuoso** [comment]
Yes ma'am,some APIs may expect headers to be explicitly set to null (NULL) e.g. Public available APIs

**Comment by ashitaprasad** [comment]
Do not bloat the generated code unnecessarily .. 
Share 1 public API which requires the header to be explicitly set as null.

**Comment by nikkivirtuoso** [comment]
ma'am please review my code, for my previous comment I apologize I thought if we use the header at every call that would be a safe call but it is not so, and there is no API which requires header explicitly set as null https://stackoverflow.com/questions/76601491/why-would-a-header-key-with-a-null-value-in-a-get-request-exist-on-some-requests
i read this problem and consider the header key as header itself Now i am clear with the thought

**Comment by ashitaprasad** [comment]
Some feedback :
Is this line in the code required ?
```
curl_easy_setopt(curl, CURLOPT_DEFAULT_PROTOCOL, "https");
```

For the POST test cases where there is multipart ex in POST4, why is a multipart/form-data header being added if the library is automatically generating and adding it internally
```
struct curl_slist *headers = NULL;
headers = curl_slist_append(headers,"Content-Type: multipart/form-data");
curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
```

Also, please adjust the new lines in the code. You don't need more than a single new line between any code block.

**Comment by nikkivirtuoso** [comment]
no ma'am we are passing the form-data
```
part = curl_mime_addpart(mime);    
    curl_mime_name(part, "text");    
    curl_mime_data(part, "API", CURL_ZERO_TERMINATED);
    
      
    part = curl_mime_addpart(mime);    
    curl_mime_name(part, "sep");    
    curl_mime_data(part, "|", CURL_ZERO_TERMINATED);
    
      
    part = curl_mime_addpart(mime);    
    curl_mime_name(part, "times");    
    curl_mime_data(part, "3", CURL_ZERO_TERMINATED);

```
that's why it is generating in the POST4 ex

**Comment by ashitaprasad** [comment]
@nikkivirtuoso Did you check if it is required as the library is automatically generating it. 
Modify the POST4 generated code and add the following feature :
- print the request headers that are being sent to the server
- Do this for both the cases - one where you are explicitly setting the header and the other where you are not
Share both the codes below which prints the request headers

**Comment by nikkivirtuoso** [comment]
code without header:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>

size_t write_callback(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    printf("%.*s", (int)(size * nmemb), ptr);
    return size * nmemb;
}

int main()
{
    CURL *curl;
    CURLcode res;
    curl = curl_easy_init();
    if (curl)
    {
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "POST");
        curl_easy_setopt(curl, CURLOPT_URL, "https://api.apidash.dev/io/form");
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

        curl_mime *mime;
        curl_mimepart *part;
        mime = curl_mime_init(curl);

        part = curl_mime_addpart(mime);
        curl_mime_name(part, "text");
        curl_mime_data(part, "API", CURL_ZERO_TERMINATED);

        part = curl_mime_addpart(mime);
        curl_mime_name(part, "sep");
        curl_mime_data(part, "|", CURL_ZERO_TERMINATED);

        part = curl_mime_addpart(mime);
        curl_mime_name(part, "times");
        curl_mime_data(part, "3", CURL_ZERO_TERMINATED);

        curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);
        curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, write_callback);
        curl_easy_setopt(curl, CURLOPT_HEADER, 1L);

        res = curl_easy_perform(curl);
        curl_mime_free(mime);
    }
    curl_easy_cleanup(curl);
    return 0;
}
```
output:
Screenshot 2024-03-22 at 2 49 37 AM


code with header:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>

size_t write_callback(char *ptr, size_t size, size_t nmemb, void *userdata)
{
    printf("%.*s", (int)(size * nmemb), ptr);
    return size * nmemb;
}

int main()
{
    CURL *curl;
    CURLcode res;
    curl = curl_easy_init();
    if (curl)
    {
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "POST");
        curl_easy_setopt(curl, CURLOPT_URL, "https://api.apidash.dev/io/form");
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
        struct curl_slist *headers = NULL;

        headers = curl_slist_append(headers, "Content-Type: multipart/form-data");
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);

        curl_mime *mime;
        curl_mimepart *part;
        mime = curl_mime_init(curl);

        part = curl_mime_addpart(mime);
        curl_mime_name(part, "text");
        curl_mime_data(part, "API", CURL_ZERO_TERMINATED);

        part = curl_mime_addpart(mime);
        curl_mime_name(part, "sep");
        curl_mime_data(part, "|", CURL_ZERO_TERMINATED);

        part = curl_mime_addpart(mime);
        curl_mime_name(part, "times");
        curl_mime_data(part, "3", CURL_ZERO_TERMINATED);

        curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);

        curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, write_callback);
        curl_easy_setopt(curl, CURLOPT_HEADER, 1L);

        res = curl_easy_perform(curl);
        curl_mime_free(mime);
        curl_slist_free_all(headers);
    }
    curl_easy_cleanup(curl);
    return 0;
}
```
output:
Screenshot 2024-03-22 at 2 48 16 AM

**Comment by nikkivirtuoso** [comment]
```
#include <stdio.h>
#include <curl/curl.h>
int debug_callback(CURL *handle, curl_infotype type, char *data, size_t size, void *userptr)
{
    if (type == CURLINFO_HEADER_OUT)
    {
        printf("Sent header: %.*s", (int)size, data);
    }
    return 0;
}

int main(void)
{
    CURL *curl;
    CURLcode res;
    curl_global_init(CURL_GLOBAL_ALL);
    curl = curl_easy_init();
    if (curl)
    {
        curl_easy_setopt(curl, CURLOPT_URL, "https://api.apidash.dev/io/form");
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "name=daniel&project=curl");
        curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, debug_callback);
        curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);

        res = curl_easy_perform(curl);
        if (res != CURLE_OK)
            fprintf(stderr, "curl_easy_perform() failed: %s\n",
                    curl_easy_strerror(res));

        curl_easy_cleanup(curl);
    }
    curl_global_cleanup();
    return 0;
}
```
output:
Screenshot 2024-03-22 at 3 05 47 AM

this is the output when i am not using the header

**Comment by nikkivirtuoso** [comment]
got it providing same formdata output for both using headers and without using headers

**Comment by nikkivirtuoso** [comment]
@ashitaprasad 
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>


int main() {
  CURL *curl;
  CURLcode res;
  curl = curl_easy_init();
  if(curl) {
    curl_easy_setopt(curl, CURLOPT_URL, "https://api.apidash.dev/io/form");
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);    
    curl_mime *mime;
    curl_mimepart *part;
    mime = curl_mime_init(curl);
      
    part = curl_mime_addpart(mime);    
    curl_mime_name(part, "asd");    
    curl_mime_data(part, "sdad", CURL_ZERO_TERMINATED);
    
    curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);
    res = curl_easy_perform(curl);curl_mime_free(mime);
    
  }
  curl_easy_cleanup(curl);
  return 0;
}
```
i was checking the content-type for this and i recieved the application/json type but i am sending a form-data and i don't think this code is wrong

**Comment by nikkivirtuoso** [comment]
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>

// Callback function to handle headers
size_t header_callback(char *buffer, size_t size, size_t nitems, void *userdata)
{
    // Check if the buffer contains "Content-Type" header
    if (strncasecmp(buffer, "Content-Type:", 13) == 0)
    {
        printf("Content-Type: %s\n", buffer + 14); // Print the content-type
    }
    return nitems * size;
}

int main()
{
    CURL *curl;
    CURLcode res;
    curl = curl_easy_init();
    if (curl)
    {
        curl_easy_setopt(curl, CURLOPT_URL, "https://api.apidash.dev/io/form");
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

        curl_mime *mime;
        curl_mimepart *part;
        mime = curl_mime_init(curl);

        part = curl_mime_addpart(mime);
        curl_mime_name(part, "asd");
        curl_mime_data(part, "sdad", CURL_ZERO_TERMINATED);

        curl_easy_setopt(curl, CURLOPT_MIMEPOST, mime);
        curl_easy_setopt(curl, CURLOPT_HEADERFUNCTION, header_callback);

        res = curl_easy_perform(curl);
        curl_mime_free(mime);
    }
    curl_easy_cleanup(curl);
    return 0;
}
```

here is the code for printing the content-type and below is the output:

Screenshot 2024-03-22 at 4 16 01 PM

**Comment by nikkivirtuoso** [comment]
@ashitaprasad ma'am done with the modifications I have used the method indication for PUT, PATCH, DELETE as for PUSH and GET lib is automatically setting it and for application/json and application/plain/text i have included in headers as it was taking wrong content-type in these cases

**Comment by ashitaprasad** [comment]
@nikkivirtuoso You need to add the print statements for printing the response code and response body in the generated code.

**Comment by nikkivirtuoso** [comment]
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>
size_t write_callback(char *ptr, size_t size, size_t nmemb, void *userdata) {
    fwrite(ptr, size, nmemb, stdout);
    return size * nmemb;
}

int main() {
    CURL *curl;
    CURLcode res;
    curl = curl_easy_init();
    if(curl) {
        curl_easy_setopt(curl, CURLOPT_URL, "https://api.apidash.dev/humanize/social?num=8700000&digits=3");  
       
        struct curl_slist *headers = NULL;
        headers = curl_slist_append(headers, "User-Agent: Test Agent");
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_callback);
        
        res = curl_easy_perform(curl);
        curl_slist_free_all(headers);
    }
    curl_easy_cleanup(curl);
    return 0;
}
```
are you saying to include this in the code ?

**Comment by nikkivirtuoso** [comment]
it is producing output if i don't include the output printing statement see:
Screenshot 2024-03-23 at 11 16 06 PM
and same output is coming if i use the above mentioned code

**Comment by ashitaprasad** [comment]
@nikkivirtuoso 
Expected Output : 
```
Response code: 200
Response body: {"data":"8.700 million"}
``` 

Your output:
```
{"data":"8.700 million"}
```

**Comment by nikkivirtuoso** [comment]
```
*   Trying 35.153.71.113:443...
* Connected to api.apidash.dev (35.153.71.113) port 443 (#0)
* ALPN: offers h2,http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=api.apidash.dev
*  start date: Mar  7 21:07:30 2024 GMT
*  expire date: Jun  5 21:07:29 2024 GMT
*  subjectAltName: host "api.apidash.dev" matched cert's "api.apidash.dev"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/1.1
> GET /humanize/social?num=8700000&digits=3 HTTP/1.1
Host: api.apidash.dev
Accept: */*
User-Agent: Test Agent

< HTTP/1.1 200 OK
< Server: nginx/1.24.0
< Date: Sat, 23 Mar 2024 18:19:34 GMT
< Content-Type: application/json
< Content-Length: 15
< Connection: keep-alive
< 
* Connection #0 to host api.apidash.dev left intact
{"data":"8.7M"}
```
will this output be considered as correct output ?

**Comment by animator** [comment]
@nikkivirtuoso No this will not work.
We have already clearly mentioned what should be the expected output.

**Comment by nikkivirtuoso** [comment]
modified the code as the need, please have a look on the code

**Comment by ashitaprasad** [comment]
Thanks for resolving all the issues. LGTM 🚀

**Pull request merged**
