### PR TITLE
Feat : Add CodeGen for Go (http)

### PR DESCRIPTION
**Pull request by CodeHariK**
Feat : Add CodeGen for Go (http) #130

### CODE REVIEW

**Comment by animator** [comment]
@CodeHariK Replace all tabs by whitespaces.

**Comment by CodeHariK** [comment]
Where

**Comment by CodeHariK** [comment]
I changed tabs to spaces in go code

**Comment by CodeHariK** [comment]
```dart
import 'package:http/http.dart' as http;

void main() async {
  var uri = Uri.parse('https://api.foss42.com');

  final response = await http.get(uri);

  int statusCode = response.statusCode;
  if (statusCode >= 200 && statusCode < 300) {
    print('Status Code: $statusCode');
    print('Response Body: ${response.body}');
  } else {
    print('Error Status Code: $statusCode');
    print('Error Response Body: ${response.body}');
  }
}
```

```go
package main

import (
  "fmt"
  "io"
  "net/http"
)

func main() {
  url := "https://api.foss42.com"
  method := "GET"
  headers := map[string]string{}

  req, err := http.NewRequest(method, url, nil)
  if err != nil {
    fmt.Println("Error creating request:", err)
    return
  }

  // Set headers
  for key, value := range headers {
    req.Header.Set(key, value)
  }

  // Make the HTTP request
  client := &http.Client{}
  resp, err := client.Do(req)
  if err != nil {
    fmt.Println("Error making request:", err)
    return
  }
  defer resp.Body.Close()

  fmt.Printf("%s\n%s\n\n", resp.Status, resp.Header)

  // Read and print the response
  bodyText, err := io.ReadAll(resp.Body)
  if err != nil {
    fmt.Println("Error reading response body:", err)
    return
  }
  fmt.Println(string(bodyText))
}
```

These two are equivalent dart and go code

Go code is generally lengthy, unlike most languages, but it is totally valid, I don't see any problem or difference in any test case.

**Comment by animator** [comment]
@CodeHariK the difference between both the codes is very evident. It is not about the length, but about what is required and what is not. Let me know when you have made the required changes to the PR.

**Comment by CodeHariK** [comment]
Please verify

**Comment by ashitaprasad** [comment]
@CodeHariK, Deleting comments is not how open source works. This is a completely unacceptable behavior. Others who might come to the PR will now have no clue about the flow of discussions that were happening. Open source is about being open to feedback, accepting mistakes and improving. Hope you respect the spirit of open source from next time.

**Comment by CodeHariK** [comment]
bro it was useless comment, in which i was comparing my old code with dart code and another one in which i added spaces instead of tabs, and i am new to this, i didn't know.

**Comment by ashitaprasad** [comment]
@CodeHariK The comments were important to the conversation at that time, post which the PR was modified. Each comment in this discussion is part of the PR history and just because any comment is no longer relevant does not mean you should delete it, as that comment led to the improvement.

**Comment by CodeHariK** [comment]
What am i supposed to do now

**Comment by ashitaprasad** [comment]
Just don't repeat it again in this project or any other open source project.

**Comment by CodeHariK** [comment]
Ok, Please verify

**Comment by animator** [comment]
@CodeHariK Can you kindly update the test cases to include example Request Models POST 4 to POST 9 which have been recently added.

**Comment by ashitaprasad** [comment]
Thanks for working on this PR.
This PR currently has issues with multipart. Hence, we have accepted an alternate PR which resolves the issue.

**Pull request closed without merging**
