### PR TITLE
feat: ability to override content type

### PR DESCRIPTION
**Pull request by nobodydotcode**
Added:

1. Content-Type header
2. Suggestions for Content-Type header values

Improvements that we can do:

1. As of now I have used the same HeaderField widget for content-type header value widget also for auto suggestions. We can write a separate widget.
2. Do we have to restrict this header only for POST requests?

### CODE REVIEW

**Comment by nobodydotcode** [comment]
@ashitaprasad Can you please review this PR whenever you have sometime?

**Comment by ashitaprasad** [comment]
Currently, we add Content-Type header [here](https://github.com/foss42/apidash/blob/3423eb7d8ff44accb75ad633b1c2a2bc9eb83111/lib/services/http_service.dart#L31) for POST request. 
To resolve the issue we need to check if `Content-Type` is already available in the `headers` map. If it is then we will not set it.

**Comment by nobodydotcode** [comment]
@ashitaprasad Done. Added the condition. Am I missing anything else? Also I see that Content type header value suggestions have been removed, I guess that is not required at this stage.

**Comment by ashitaprasad** [comment]
@nobodydotcode The value of [`HttpHeaders.contentTypeHeader`](https://api.dart.dev/stable/3.2.4/dart-io/HttpHeaders/contentTypeHeader-constant.html) is `"content-type"`. What if the user enters `Content-Type` as the header field name. 
The current check you have added will fail.

Also, content type header value suggestions have been removed because the user is already providing it via content type dropdown in the Body. This feature is actually a corner case where the user explicitly wants to specify the content type because the API wants some additional info in it as well like charset.

**Comment by nobodydotcode** [comment]
@ashitaprasad I have corrected the check. And I have added one more commit for codegen. And as a condition I think following would be enough.

`headers.keys.any((k) => k.toLowerCase() == HttpHeaders.contentTypeHeader)`

**Comment by ashitaprasad** [comment]
Thank @nobodydotcode I will review the chnages.

**Comment by ashitaprasad** [comment]
Thanks for the PR @nobodydotcode 🙌
LGTM 🚀
Fixes #90

**Pull request merged**
