### PR TITLE
Add feature Websocket Support

### PR DESCRIPTION
**Pull request by mmjsmohit**
## PR Description

This pull request introduces basic support for WebSockets, following the specifications discussed in issue #15. The changes include modifications to tests to align with the new request and response model. While the initial implementation is in place, there are still some outstanding issues that need resolution, along with additional test coverage.

### Key Changes

1. **WebSocket Integration**: The PR establishes bidirectional communication channels between clients and servers using the WebSocket protocol. This enables real-time data exchange without breaking the connection or requiring additional HTTP requests.

2. **Test Updates**: The existing tests have been adapted to match the new request and response patterns. However, further testing and validation are necessary to ensure robustness.

### Next Steps

1. **Write Tests**: Comprehensive test coverage is essential. We need to create test cases that cover various scenarios, including edge cases.
2. **Enhance UI**: I would like to enhance the UI including adding icons for protocols and improving the user experience for dealing with realtime API testing.
3. **Error Handling**: Build robust error handling for Websockets. 

## Related Issues

- Related Issue #15

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_
- [x] I need help with writing tests

### CODE REVIEW

**Comment by sebastianbuechler** [comment]
@mmjsmohit I just checked out your PR and I'm afraid there are major issues with the core WebSocket support. I'm getting null check errors through much of the testing and basic feature like connection states for multiple connections are wrong. Since my PR is already fully functional maybe we can see how to integrate with eachother. What do you think?

**Comment by animator** [comment]
@mmjsmohit Please make this change https://github.com/foss42/apidash/issues/307

**Comment by ashitaprasad** [comment]
@mmjsmohit Can you please resolve the conflicts and let us know

**Comment by mmjsmohit** [comment]
Sure @ashitaprasad! Will make a new PR with resolved conflicts and issues after I finish implementing MQTT.

**Pull request closed without merging**
