### PR TITLE
Adding codegen for Python using Request.

### PR DESCRIPTION
**Pull request by Mixel2004**

### CODE REVIEW

**Comment by animator** [comment]
Hi @Mixel2004 
Thank you for adding Python codegen. 
Can you please also open an issue and link this PR to the issue as described [here](https://github.com/foss42/api-dash/issues/35).
Once done we will start with the review process.

**Comment by Mixel2004** [comment]
#64

**Comment by animator** [comment]
Hi @Mixel2004 
The generated codes are incorrect.

For example,
Screenshot 2023-06-25 at 2 18 19 PM

Screenshot 2023-06-25 at 2 22 07 PM

Please take a look at the various test cases in `/test/codegen/kotlin_okhttp_codegen_test.dart`

**Comment by Mixel2004** [comment]
@animator Sorry for my previous mistakes I have fixed the code could you please review it.

**Comment by animator** [comment]
Hi @Mixel2004 Please take a look at the Dart codegen and try to understand how the template works.
For example - GET http.cat/400

```python
import requests
import json

def main():
    url = 'https://http.cat/400'

    params = { 
    }

    data = ''''''


    headers = {
                  "content-type": "text/plain"
                }

    response = requests.get(
        url, params=params, headers=headers, data=data
    )

    status_code = response.status_code
    if 200 <= status_code < 300:
        print('Status Code:', status_code)
        print('Response Body:', response.text)
    else:
        print('Error Status Code:', status_code)
        print('Error Response Body:', response.text)

main()
```

The corresponding Dart code is 

``` dart 
import 'package:http/http.dart' as http;

void main() async {
  var uri = Uri.parse('https://http.cat/400');

  final response = await http.get(uri);

  int statusCode = response.statusCode;
  if (statusCode >= 200 && statusCode < 300) {
    print('Status Code: $statusCode');
    print('Response Body: ${response.body}');
  }
  else{
    print('Error Status Code: $statusCode');
    print('Error Response Body: ${response.body}');
  }
}
```

You can see how various lines generated by the Python codegen is not required.

**Comment by animator** [comment]
Also, kindly submit tests cases along with the code changes.
Test cases go here 👉 [`test/codegen`](https://github.com/foss42/api-dash/tree/main/test/codegen)
And you can run the tests following the instructions provided [here](https://github.com/foss42/api-dash/blob/main/CONTRIBUTING.md#how-to-run-tests)

**Comment by Mixel2004** [comment]
Hi @animator 
Kindly review the completed changes and provide feedback. Thank you

**Comment by animator** [comment]
The generated code is still not correct.
Screenshot 2023-07-08 at 7 07 01 PM



It works in API Dash (status 200)
Screenshot 2023-07-08 at 7 07 56 PM


You need to take a look at the documentation of requests library a bit more and do more testing.

**Comment by Mixel2004** [comment]
For some reason, json.load was causing problems but I assume it was a server error while testing. Now I have updated it and also checked all the tests I have the page where I did the test of the python code generated by it.
[tests.pdf](https://github.com/foss42/api-dash/files/11991392/tests.pdf)

**Comment by animator** [comment]
The produced code is still incorrect ... I recommend you to go through this [file](https://github.com/foss42/api-dash/blob/main/lib/codegen/dart/pkg_http.dart) and understand each and every line of it as it covers various corner cases not covered in this PR. In case you have any doubt just post it in the #foss channel of Discord and we will be happy to help.
Also, I am not sure if you are aware .. that requests library provides a parameter `json` which reduces the code lines as now you don't have to mention the content type header is json. I will recommend you to not be in a hurry to make fixes and spend some time to make the code more robust.

**Pull request merged**
