### PR TITLE
refine header suggestions using FuzzyOptions

### LINKED ISSUE #207: Implement fuzzy string matching to get header suggestions
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Currently, header suggestions are a sequence of strings which contain the given substring with no logic implemented for ordering. Algorithms like [fuzzy string search](https://redis.com/blog/what-is-fuzzy-matching/) etc. can be used to provide the sequence of matching strings with the most relevant item at the top.

### PR DESCRIPTION
**Pull request by PratyushChauhan**
## PR Description

This PR adds fuzzy logic while getting header suggestions. I have reviewed the previous PR and have used FuzzyOptions to filter out irrelevant results.

## Related Issues

- Related Issue #207
- Closes #207

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [x] No, and this is why: _I need help in deciding what test cases will be relevant for this feature._

### CODE REVIEW

**Comment by PratyushChauhan** [comment]
I noticed that upon typing `Allow-Methods` it does not return `Access-Control-Allow-Methods` .  Finding a fix for this rn.

**Comment by PratyushChauhan** [comment]
Added tests that are identical to the previous suggestion functions. However there are some failed test cases. 

Here, the `Access-Control-Allow-Headers`  pattern should only return one element but it returns 4. Currently working to pass this test case. This is most likely due to the large edit distance of 50.

```
Testing getFuzzyHeaderSuggestions function Testing using Access-Control-Allow-Headers [E]
  Expected: ['Access-Control-Allow-Headers']
    Actual: [
              'Access-Control-Allow-Headers',
              'Access-Control-Allow-Methods',
              'Access-Control-Allow-Origin',
              'Access-Control-Request-Headers'
            ]
```

**Comment by animator** [comment]
It is currently not performing better than the existing solution.
Also, the tests are failing.
The purpose is to provide better results, so make sure you test it thoroughly for different scenarios and provide a short description in the PR next time describing where it is performing better than the existing implementation.
Closing this PR.

**Comment by PratyushChauhan** [comment]
Continued in pr #380

**Pull request closed without merging**
