### PR TITLE
Added : HTTP headers suggestions #107

### PR DESCRIPTION
**Pull request by tanishgl**
**PR Description** 
1. I've added a few HTTP headers suggestions into the existing list.
2. I've created a test file for the same.

**Outcome**
This will make the headers suggestions list more exhaustive and complete w.r.t CORS related headers.

**Testing**
I have added a test file for the headers suggestions list to test for newly added suggestions. For headers prefixed with "Access-Control", I've added 2 tests per header to test for complete header name and the suffix.

### CODE REVIEW

**Comment by ashitaprasad** [comment]
Thanks for the PR @tanishgl.
I have added my feedback.
Also, can you please add more commonly used headers (don't need to add a test for each & every header).

**Comment by tanishgl** [comment]
@ashitaprasad 
Thank you so much the feedback. I will add more commonly used headers and refactor tests as you suggested.

**Comment by ashitaprasad** [comment]
Thank you for the PR @tanishgl 🙌
LGTM 🚀

**Comment by tanishgl** [comment]
> Thank you for the PR @tanishgl 🙌 LGTM 🚀

Thank you so much!

**Pull request merged**
