### PR TITLE
Feat search requests

### LINKED ISSUE #305: Add a search/filter for collection pane
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add a search/filter bar at the top of the collection pane to make it easy for users to filter requests based on name or url.

### PR DESCRIPTION
**Pull request by yashas-hm**
## PR Description
This allows a user to search request based on name or url. When no request found an indicative text will be shown.

Fixed Renderflex issue in codegen language dropdown. 

## Related Issues
- Related Issue #305
- Resolves #305

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
- [x] No, and this is why: Wasn't sure which tests to include

https://github.com/foss42/apidash/assets/64674824/bec61355-cb22-439a-aae6-79cc27cd1fc2

### CODE REVIEW

**Comment by yashas-hm** [comment]
@ashitaprasad fixed the bug with last PR

**Comment by animator** [comment]
I would like you to spend some time on the problem and think it through.
Do you even require any provider to solve this problem?

**Comment by yashas-hm** [comment]
I had implemented the search provider as a failsafe to show a circular loader when searching queries (loader UI change was not pushed with the commits somehow) in a big list or queries. I removed it now as I tested using 100 requests and there was no visible lagging in showing the filtered list.

**Comment by animator** [comment]
Review your code. The approach is still incorrect. This feature can be implemented at UI level without touching providers.

**Comment by yashas-hm** [comment]
I am manipulating only the request sequence provider to trigger UI change using a filter function in collection provider. Could you provide your thought for the filtering approach? 

I can relocate the filter function outside the provider but manipulating the request sequence would be necessary to trigger the UI change.

**Comment by animator** [comment]
This feature has been implemented. Closing this PR.

**Pull request closed without merging**
