### PR TITLE
ruby faraday code gen PR

### LINKED ISSUE #147: Add CodeGen for Ruby (faraday)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Ruby
Library - https://github.com/lostisland/faraday

### PR DESCRIPTION
**Pull request by nikkivirtuoso**
## PR Description

_Add your description_
this PR will generate the API request code for ruby using faraday library
## Related Issues

- Related Issue #147 
- Closes #147

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_
- [ ] I need help with writing tests

### CODE REVIEW

**Comment by nikkivirtuoso** [comment]
Screenshot 2024-02-28 220447
Screenshot 2024-02-28 220453

**Comment by nikkivirtuoso** [comment]
@animator sir please have a look sir i have updated the codes

**Comment by animator** [comment]
@nikkivirtuoso Can you kindly update the test cases to include example Request Models POST 4 to POST 9 which have been recently added.

**Comment by animator** [comment]
Kindly open a new PR from the project's latest main branch covering all test cases and verifying the generated code in your local computer.

**Pull request closed without merging**
