### PR TITLE
 Add Multipart tests to NodeJS Fetch Codegen

### LINKED ISSUE #282: Update test script for nodejs (fetch) codegen
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

New example requests have been added - **POST 4 to POST 9** in [test/request_models.dart](https://github.com/foss42/apidash/blob/main/test/request_models.dart) which tests multipart formdata functionality of the codegens. These request models need to be included in the test script for **nodejs (fetch)** codegen. And the result generated must be verified by running it locally before adding it to the test file as the expected code. 

See example test script for [Python (requests)](https://github.com/foss42/apidash/blob/main/test/codegen/python_requests_codegen_test.dart) which covers all the test cases.

To learn more about codegens check out #80

### PR DESCRIPTION
**Pull request by Tanish2002**
## PR Description
Added Posts Test 4-9 for multipart form testing for NodeJS Fetch Codegen.

## Related Issues
- Closes #282

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
- [x] Yes

### CODE REVIEW

**Comment by animator** [comment]
Have you manually verified whether POST 4- POST 9 generated code are working correctly?
I ran it at my end and they are not working.

**Comment by Tanish2002** [comment]
@animator I'm sorry. I assumed the codegen was already working fine and I only needed to add the test cases.
Upon confirming on my end as well, they don't seem to work.

I've looked at the codegen for fetch and it seems to be broken for form-related requests.
Do I implement the fixes in a separate PR and then rebase this pr or just fix it in this PR?

**Comment by animator** [comment]
@Tanish2002 If something is not tested, we should not assume it is correct. One of the reasons why we are doubling down on testing. I think it would be a good idea to create 2 new PRs .. 
One for JS & NodeJS (fetch) and another for JS & NodeJS (axios) as JS & NodeJS share a single codebase.
I will go ahead and close all the 4 PRs.

**Comment by Tanish2002** [comment]
@animator can you please check the discord channel. I've tagged you there since I don't think it's appropriate to continue the discussion in a closed PR.

**Pull request closed without merging**
