### PR TITLE
FIX #136: Added CodeGen for Java (async-http-client)

### LINKED ISSUE #136: Verify CodeGen & add test cases for Java (async-http-client)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Java
Library - [async-http-client](https://github.com/AsyncHttpClient/async-http-client)

More info here - #80

### PR DESCRIPTION
**Pull request by AcousticDeveloper**
## PR Description

This PR adds automated code generation for Java's async-http-client library.

## Related Issues

- Related Issue #136 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
- [x] No, I am working on adding tests. I need a little clarification about whether to include the main function and import packages in the generated code. I will create commits and push the testing code into this PR as soon as these doubts are resolved, and tests have written properly.

### CODE REVIEW

**Comment by Drakennnnn** [comment]
Hey @AcousticDeveloper, I have been working on this issue for a while and I am glad to see one more participant working on this.  Your dart file covers everything and like u mentioned, you've been working on adding tests. Yes, I believe we should include main function and import packages in the generated code. If you are willing to work together I can share you the code with all the test required to perform. I have used CompletableFuture, it starts an asynchronous task that executes the code inside the lambda expression provided to it. Also used CompletableFuture<HttpResponse<String>>, to ensure the response in the future. Thread.sleep(2000) is added to prevent the program from terminating immediately before the asynchronous task completes. Might need to handle this differently based on the application and should ensure should termination before task. I used the sync http client as reference from the issue.

**Comment by Drakennnnn** [comment]
I wasnt able to attach a dart file, so heres the code. 

Regards,
Sudip

**Comment by animator** [comment]
@AcousticDeveloper Please add test cases in the commit. In the file, also include test cases example Request Models POST 4 to POST 9 which have been recently added.

**Comment by AcousticDeveloper** [comment]
> @AcousticDeveloper Please add test cases in the commit. In the file, also include test cases example Request Models POST 4 to POST 9 which have been recently added.

@animator I have added the test cases and multipart body support and created a new PR #355.

**Pull request merged**
