### PR TITLE
Add feat codegen for Kotlin using retrofit

### LINKED ISSUE #247: Adding codegen for Kotlin using Retrofit
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I want to add a new code generation language for Kotlin using Retrofit. Currently, there is no support for generating code for Kotlin with Retrofit in our system.

**Describe the solution/feature you'd like us to add**
I would like to see support for generating Kotlin code with Retrofit in our code generation system. This would involve creating templates and logic for generating Kotlin code that utilizes Retrofit for making API calls.

**Any other feedback you would like to provide regarding the site**
Overall, I find the site quite useful, but adding support for more new codegen languages would greatly enhance its capabilities and usefulness for developers

### PR DESCRIPTION
**Pull request by Photon3009**
## PR Description

This PR introduces support for generating Kotlin code using Retrofit for API communication. Retrofit is a type-safe HTTP client for Android and Java by Square, Inc., that makes it easy to consume RESTful web services

Description of image

## Related Issues

- Related Issue #247 
- Closes #247

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by animator** [comment]
`flutter test` is failing for 4 test cases. Recheck.

**Comment by Photon3009** [comment]
okay

**Comment by Photon3009** [comment]
@animator please now check, I've updated the pr

**Comment by animator** [comment]
@Photon3009 Few points:

- Your generated kotlin code has `ResponseBody` class. What is the structure of this class? how will the user know.

 - You need to write test cases for all the request models as described [here](https://github.com/foss42/apidash/discussions/80). For example, see test file for Python or cURL.

- As the user needs to perform additional tasks to run this generated code, you need to document an example with full steps showing how to do so. So that we can provide a link to the user to learn more. See example for JS (fetch) [in this comment](https://github.com/foss42/apidash/issues/293#issuecomment-1995208098)

**Comment by Photon3009** [comment]
hey @animator, please check the example below. If it works, then I will write the remaining tests for this. Otherwise, let me know if we need to add code to print a generic response in the generated code too

<details>
  <summary>Structure of Response Body</summary>
The `ResponseBody` class in Retrofit is a generic class that represents the body of an HTTP response. To handle the response properly, you should define a data class that matches the structure of the JSON response you're expecting. For example, if you're fetching user data from an API, your data class might look something like this:

```kotlin
data class User(
    val id: String,
    val name: String,
    val email: String
)
```
</details>

<details>
  <summary>The actual generated code</summary>

```kotlin
import retrofit2.Call
import retrofit2.http.GET
import retrofit2.http.Query

interface ApiService {
    @GET("/api/")
    fun getUser(@Query("format") format: String): Call<ResponseBody>
}

fun main() {
    val service = Retrofit.Builder()
        .baseUrl("https://randomuser.me")
        .addConverterFactory(GsonConverterFactory.create())
        .build()
        .create(ApiService::class.java)

    // Call your API methods here using service object
}

```
</details>

<details>
  <summary>Complete Example in Koltin</summary>

```kotlin
import retrofit2.Call
import retrofit2.http.GET
import retrofit2.http.Query

interface ApiService {
    @GET("/api/")
    fun getUser(@Query("format") format: String): Call<User>
}
fun main() {
    val service = Retrofit.Builder()
        .baseUrl("https://randomuser.me")
        .addConverterFactory(GsonConverterFactory.create())
        .build()
        .create(ApiService::class.java)

    val call = service.getUser("json")
    call.enqueue(object : Callback<User> {
        override fun onResponse(call: Call<User>, response: Response<User>) {
            if (response.isSuccessful) {
                val user = response.body()
                println("User ID: ${user?.id}, Name: ${user?.name}, Email: ${user?.email}")
            } else {
                println("Error: ${response.errorBody()}")
            }
        }

        override fun onFailure(call: Call<User>, t: Throwable) {
            println("Failed to fetch user: ${t.message}")
        }
    })
}

```
</details>

**Comment by animator** [comment]
Can you add the remaining test cases.

**Comment by Photon3009** [comment]
sorry for the delay, currently going through my exams, will complete this asap, probably within two days

**Comment by animator** [comment]
No problem. Good luck for the exams.

**Comment by Photon3009** [comment]
Thanks @animator 
I have updated the test cases!

**Comment by Photon3009** [comment]
@animator did you check this?

**Comment by animator** [comment]
As announced in the discord server, we are busy with application reviews and all PR reviews are on hold.

**Comment by Photon3009** [comment]
okay!

**Comment by animator** [comment]
The generated code for POST with form fields are incorrect.
Add complete working examples in comment for the below cases:
- GET 8
- POST 2
- POST 4
- POST 6

**Comment by animator** [comment]
Please raise a new PR after ironing out everything.

**Pull request closed without merging**
