### PR TITLE
feat: Add a search/filter for collection pane

### LINKED ISSUE #305: Add a search/filter for collection pane
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Add a search/filter bar at the top of the collection pane to make it easy for users to filter requests based on name or url.

### PR DESCRIPTION
**Pull request by sudhar08**
This feature adds a search/filter functionality to the collection pane, allowing users to easily search for specific requests based on their names. Users can input search queries to filter the requests displayed in the collection pane, improving the navigation and organization of requests within the application.

## PR Description

_Add your description_

## Related Issues

- Related Issue #305 
- Closes #305 

### Checklist
- [ x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x ] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by ashitaprasad** [comment]
@sudhar08 Review your approach. This feature can be implemented at UI level without touching providers.

**Comment by sudhar08** [comment]
@ashitaprasad we can't implement this feature without the provider because we need the  data to search

**Review by sudhar08 — COMMENTED** [review]
Check out this file

**Comment by animator** [comment]
@sudhar08 All required data is already flowing into `collection_pane.dart`

**Comment by animator** [comment]
You just need at max one provider to store search query, but nothing more other than that.

**Comment by sudhar08** [comment]
> You just need at max one provider to store search query, but nothing more other than that.

Yes I need one provider for store the search query

**Comment by animator** [comment]
But, no other modification is required in `CollectionStateNotifier` that you have currently done.
Also, the provider for storing search query goes in `ui_providers.dart`

**Comment by sudhar08** [comment]
> But, no other modification is required in `CollectionStateNotifier` that you have currently done.
> Also, the provider for storing search query goes in `ui_providers.dart`

What I was done here is the when the user search the query store in the provider and it and it search for the query in the `CollectionStateNotifier`

**Pull request merged**
