### PR TITLE
Feat delete multiple requests

### LINKED ISSUE #319: Select and delete in groups
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
There should be a selection button  or the user is able to drag and select so that user can select and delete the unwanted collections,files or folders in groups rather than selecting and deleting them one by one.

### PR DESCRIPTION
**Pull request by yashas-hm**
## PR Description
This PR allows the user to select and delete multiple requests

## Related Issues

- Related Issue #319 
- Closes #319 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
- [ ] Yes
- [x] No, and this is why: not sure which tests to be added

### Screenshot
Screenshot 2024-03-18 at 5 06 57 PM

### CODE REVIEW

**Comment by yashas-hm** [comment]
@animator please review

**Comment by ashitaprasad** [comment]
@yashas-hm This PR is not working as demonstrated in the image above. Before you raise a PR, please test at your end and ensure that the code is working.

Screenshot 2024-03-20 at 12 21 56 AM

**Comment by yashas-hm** [comment]
@ashitaprasad  the delete option will come on long press of the request card. Sowing the select box always would hamper UX. We can add this in documentation or something to make users aware of this.

**Comment by yashas-hm** [comment]
I'll create a new PR with a better description.

**Pull request closed without merging**
