### PR TITLE
update: test cases added from POST4 to POST9 for dart (http)

### LINKED ISSUE #291: Update test script for dart (http) codegen
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

New example requests have been added - **POST 4 to POST 9** in [test/request_models.dart](https://github.com/foss42/apidash/blob/main/test/request_models.dart) which tests multipart formdata functionality of the codegens. These request models need to be included in the test script for **dart (http)** codegen. And the result generated must be verified by running it locally before adding it to the test file as the expected code. 

See example test script for [Python (requests)](https://github.com/foss42/apidash/blob/main/test/codegen/python_requests_codegen_test.dart) which covers all the test cases.

To learn more about codegens check out #80

### PR DESCRIPTION
**Pull request by nikkivirtuoso**
## PR Description

as the dio package has been updated I have fixed the code according to the package and included the testcases POST4-9

## Related Issues

- Related Issue #291 
- Closes #291 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by nikkivirtuoso** [comment]
all test cases have successfully passed
Screenshot 2024-03-14 at 1 57 24 PM

**Comment by animator** [comment]
@nikkivirtuoso all test cases have passed, but have you run the codes generated by POST4 - POST9 locally to verify that it actually works.

**Comment by nikkivirtuoso** [comment]
@animator wait checking for null conditions

**Comment by nikkivirtuoso** [comment]
@animator please have a look i have updated the test cases and handled the null values now it will be able to compile and work properly

**Comment by ashitaprasad** [comment]
LGTM 🚀

**Pull request merged**
