### PR TITLE
rust NET:HTTP code gen 

### LINKED ISSUE #148: Add CodeGen for Ruby (Net::HTTP)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Ruby
Library - https://github.com/ruby/net-http

### PR DESCRIPTION
**Pull request by nikkivirtuoso**
## PR Description
this PR will produce the code for rust API requests using NET:HTTP
_Add your description_

## Related Issues

- Related Issue #148 
- Closes #148 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [ ] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_
- [x] I need help with writing tests

### CODE REVIEW

**Comment by nikkivirtuoso** [comment]
Screenshot 2024-02-28 215721
Screenshot 2024-02-28 215736

**Comment by nikkivirtuoso** [comment]
sir please have a look i have corrected the code

**Comment by nikkivirtuoso** [comment]
@animator @ashitaprasad

**Comment by nikkivirtuoso** [comment]
Screenshot 2024-03-01 182404
corrected one

**Comment by animator** [comment]
@nikkivirtuoso Can you kindly update the test cases to include example Request Models POST 4 to POST 9 which have been recently added.

**Comment by ashitaprasad** [comment]
You have tagged incorrect issue. Tag the correct issue or create a new one.

**Comment by animator** [comment]
Closing this issue as it links to ruby http issue and contains rust code.
You can open a new issue and a new PR .. along with test cases and instructions to run the code in local computer.

**Pull request closed without merging**
