### PR TITLE
Feature request: Support environment variables

### PR DESCRIPTION
**Pull request by vidya-hub**
### Environment Variables Support **(Under Development)** #25

1. Introducing the **Environment** tab for seamlessly incorporating environment variables in API requests within ApiDash.
2. Users gain the ability to effortlessly manage multiple environments, with the freedom to create, edit, and delete variables within each environment.
3. Select and utilize specific environments, tapping into their associated variables, when sending API requests from the requests page.

### CODE REVIEW

**Comment by ashitaprasad** [comment]
Hi @vidya-hub 
Is the PR ready for review?

**Comment by vidya-hub** [comment]
Hi @ashitaprasad 

No,
Actually I am working on it.

Once it's done I'll update you.

Thank you.

**Comment by ashitaprasad** [comment]
Sure @vidya-hub. 
Can you kindly provide a checklist like the one mentioned below so that we can identify the tasks that have been completed and identify the remaining issues.

- [x] Task 1 - A new tab to manage ....
- [x] Task 2 - Persistence of env vars ..
- [ ] Task 3 - Allow users to ....
- [ ] Issue 1 - Issue with ....

Thanks!

**Comment by vidya-hub** [comment]
Hi @ashitaprasad 

here is the checklist,

- [x] A new tab to manage environments and environment variables,
- [x] Persist the state of different environments,
- [x] Allow Users to change the environments in API Request Pane,
- [ ] Allow users to select the environment variables as auto suggestion feature from the active environment in different API parameters fields,
- [ ] Reflect the selected environment variables with there actual environment values while sending the request with code gen support,
- [ ] Persist the entire environments data in Local DB.

The last 3 key features that i am working on once these are finished i will update you.

Thank you!

**Comment by ashitaprasad** [comment]
Thanks for the checklist @vidya-hub 👍

**Comment by vidya-hub** [comment]
Hi @ashitaprasad,

I've added the basic implementation,

- [x] A new tab to manage environments and environment variables,
- [x] Persist the state of different environments,
- [x] Allow Users to change the environments in API Request Pane,
- [x] Allow users to select the environment variables as an auto-suggestion feature from the active environment in the URL field (will give support for other request fields as well in the future )
- [x] Reflect the selected environment variables with their actual environment values while sending the request

Screenshot 2024-02-16 215907
Screenshot 2024-02-16 215844
Screenshot 2024-02-16 215757
Screenshot 2024-02-16 215737
Screenshot 2024-02-16 215516


This is not a complete approach but it is a core-level working approach,
Can you please review the code and the functionality with UI,
Please provide the feedback,
So that I can finish the other modules that are pending on the checklist.

**Comment by ashitaprasad** [comment]
Thank @vidya-hub 
I will review the PR.

**Comment by mjablecnik** [comment]
@ashitaprasad Hello, so what is state of this PR? I see it is here for a long time without any changes..

**Comment by ashitaprasad** [comment]
New version is in progress at #412

**Pull request closed without merging**
