### PR TITLE
Generate android and iOS files

### LINKED ISSUE #33: Mobile Android/ iOS Support
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I would like to add support for Mobile Platforms i.e. Android, iOS this would allow to test APIs on-the-go. It might seem excessive and unnecessary but this kind of agility that enables everyone to test stuff on-the-go, having the same familiar UX and set of features providing continuity, with the added benefit of having a shared open-source codebase powered by flutter is what could potentially set this app apart from other competition.

**Describe the solution/feature you'd like us to add**
My proposal is building a preliminary mobile version of the app with a simplified UI/UX that can empower users to test APIs and endpoints in the simplest way possible on-the-go. This could potentially be utilized in adding future features like integrating a cross-platform sync; providing continuity for signed-up users.

**Approach**
This is obviously a fairly big feature to be added, for that my approach would be to start
1. Designing an interface with the bare minimum of functional features coupled with the same beautiful design, (no changes, just adapting for smaller screens)
2. Iteratively develop/ adapt code for the new platforms (starting with Android because it's usually more accessible)
3. Test and add more features while maintaining this simple design language.

### PR DESCRIPTION
**Pull request by Yousef-Rabia**
**What kind of change does this PR introduce?**

This PR introduces the addition of IOS and Android files to the project, enabling the implementation of mobile permissions such as internet access and storage access (e.g., for utilizing API packages) and facilitating native features like splash screens and app icons. Additionally, it includes edits to `android/app/build.gradle` , enabling multiDexEnabled and setting minSdkVersion to 21, ensuring compatibility with a wider range of developers devices.

**Issue Number:**

Fixes #33

### CODE REVIEW

**Comment by Yousef-Rabia** [comment]
review please
 @animator @ashitaprasad

**Comment by ashitaprasad** [comment]
We will get back to you after review.

**Comment by animator** [comment]
Instead of adding Android & iOS platform files we have added a new [Troubleshooting Common Issues](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md#troubleshooting-common-issues) section where one can provide any platform specific instruction. Please feel free to open a new PR adding the same there.

**Comment by Yousef-Rabia** [comment]
@animator 
I can't found this section

**Comment by DenserMeerkat** [comment]
> @animator 
> I can't found this section

It's the last section in the Contributing doc.
[CONTRIBUTING.md](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)

**Pull request closed without merging**
