### PR TITLE
Add HTML Rendering

### PR DESCRIPTION
**Pull request by mmjsmohit**
This PR aims to solve #155 
I have used `flutter_widget_from_html` which convert html into flutter widgets so that they can be previewed in the preview pane.

### CODE REVIEW

**Comment by animator** [comment]
Expected Response:

Screenshot 2024-02-23 at 7 12 45 AM

This PR:
Screenshot 2024-02-24 at 6 39 31 AM

**Comment by mmjsmohit** [comment]
Hi @animator! The goal of this PR was to add HTML rendering, however it looks like I need to simply add a webview. Should I go ahead with that?

**Comment by animator** [comment]
I had already shared more details with you on discord, in case you missed it.
Screenshot 2024-02-24 at 9 09 01 AM

WebView is a solution you can explore.

**Comment by monstajoe2002** [comment]
Can I work on this issue please?

**Comment by animator** [comment]
Sure @monstajoe2002

**Comment by monstajoe2002** [comment]
> I had already shared more details with you on discord, in case you missed it. Screenshot 2024-02-24 at 9 09 01 AM
> 
> WebView is a solution you can explore.

Unfortunately, that's not possible with desktop apps in Flutter since the `WebView` feature is mobile only. Even then, desktop implementations don't work 100% especially when we don't have access to the request url from its repective widget.

**Comment by monstajoe2002** [comment]
Hey guys! I created a pull request for this feature here: https://github.com/foss42/apidash/pull/243

**Pull request closed without merging**
