### PR TITLE
Resolve issue mobile android/ ios support

### LINKED ISSUE #33: Mobile Android/ iOS Support
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I would like to add support for Mobile Platforms i.e. Android, iOS this would allow to test APIs on-the-go. It might seem excessive and unnecessary but this kind of agility that enables everyone to test stuff on-the-go, having the same familiar UX and set of features providing continuity, with the added benefit of having a shared open-source codebase powered by flutter is what could potentially set this app apart from other competition.

**Describe the solution/feature you'd like us to add**
My proposal is building a preliminary mobile version of the app with a simplified UI/UX that can empower users to test APIs and endpoints in the simplest way possible on-the-go. This could potentially be utilized in adding future features like integrating a cross-platform sync; providing continuity for signed-up users.

**Approach**
This is obviously a fairly big feature to be added, for that my approach would be to start
1. Designing an interface with the bare minimum of functional features coupled with the same beautiful design, (no changes, just adapting for smaller screens)
2. Iteratively develop/ adapt code for the new platforms (starting with Android because it's usually more accessible)
3. Test and add more features while maintaining this simple design language.

### PR DESCRIPTION
**Pull request by MohammedAshraf19**
## PR Description

I made my own design with almost reuse of all desktop components, I think that design more comfortable for new user and old user that use desktop app.
It not finish yet and I have many idea to make it more completely.
[My Demo](https://drive.google.com/drive/folders/1pHtQIxAq3BrpH6ab54wWQizRETeBaQAx?usp=sharing)

## Related Issues

- Related Issue #33 
- Closes #33 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [ ] Yes
- [x] No, and this is why: the features and code are still in implementation phase.

### CODE REVIEW

**Comment by MohammedAshraf19** [comment]
Hi @animator @ashitaprasad 
In your opinion this design is good for what you want or Use mock-up design that suggested by @animator  with Modal Bottom Sheet for Response will better or implement this design in screen?
Design

**Comment by animator** [comment]
Hi @MohammedAshraf19 

Some feedback:
- In MobileHome you need to watch the selectedId provider and show a progress indicator if it is null.
- What is the rationale behind implementing View Code as bottomsheet? If the code requires scrolling, the scroll bars are a bit weird and are obstructing the code. (image below)

scroll bar in codegen

- What is the rationale behind implementing Response as a bottomsheet? It is not allowing us to utilise the full screen space. Once the response sheet is dismissed there is no way to view it again unless the user sends a new request. (image below)

response bottomsheet

- The name of the request is not shown in the app bar (along with a icons to rename & delete)
- The theme, colors, padding of the requests in the collection pane (drawer) needs improvement to go with our current desktop look. (image below)

collection pane

**Comment by MohammedAshraf19** [comment]
Hi @animator and Thank for your feedback and It is my answer for your feedback

1-yes, I know this mistake and I will Solve it.

2- I think It give user freedom to interactive with view code and his request in the same screen, he can min the bottom sheet to show what he typed in request and I will remove the scroll bar to make design simple for mobile.

3-
- It give user freedom to interactive with response and  request in the same screen with out move from screen to another and user won't close bottom sheet only if he want to edit some things in his request.
- if user got error in response, he can read error and see what he typed in request in same screen (it easy for him rather than move between screen).
- I can make bottom sheet take 75% of screen or 100% if it better or you have another suggest for me?

4- I think it not important because user when he type api the name of request change automatic and if user want change request name he can change in collection pane(I user appbar to make easy move between setting and Intro page).

5- I just change padding of drawer because if user create more request, he can't scroll cause elements is close each other(If you remove padding and try to scroll in real device you will can not scroll with out use the scroll bar).

**Comment by MohammedAshraf19** [comment]
Hi @animator  I make Some Change I my code and solve selectId problem.
I was thinking a lot in Bottom sheet problem that user should tap in send button every time to send so I suggest to make bottom sheet down that user can drop up to show response, like this [package](https://pub.dev/packages/solid_bottom_sheet), so can I use it and it is better ?

**Comment by ashitaprasad** [comment]
Thanks for this PR.
Closing this PR as it has been assigned as a GSoC project.

**Pull request closed without merging**
