### PR TITLE
feat : Codegen for Swift (URLSession)

### LINKED ISSUE #140: Add CodeGen for Swift (URLSession)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for Swift 
Library - [URLSession](https://developer.apple.com/documentation/foundation/urlsession)

Guidelines for adding a codegen - https://github.com/foss42/apidash/discussions/80

### PR DESCRIPTION
**Pull request by deepraj02**
## PR Description

Added Codegen support for **URLSession** (swift)

## Related Issues

- Related Issue #140 
- Closes #140 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
Status : **All Tests Passing**

- [x] Yes
- [ ] No, and this is why: 

## Preview

https://github.com/user-attachments/assets/fd6a84a7-b707-43b2-a2ee-ce642424aa1d

### CODE REVIEW

**Comment by ashitaprasad** [comment]
Default timeout should be as it is. No infinity should be specified.

**Comment by ashitaprasad** [comment]
Much more elegant solution to multipart-formdata is required.
You can explore some popular packages. Some examples:
https://swiftpackageindex.com/FelixHerrmann/swift-multipart-formdata
https://swiftpackageindex.com/Kuniwak/MultipartFormDataKit

**Comment by deepraj02** [comment]
on it.

**Comment by ashitaprasad** [comment]
Is this PR ready for review @deepraj02

**Comment by deepraj02** [comment]
Adding tests, and some minor refactors, will be ready by this week

**Pull request merged**
