### PR TITLE
Codegen c (libcurl)

### LINKED ISSUE #138: Add CodeGen for C (Libcurl)
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

Add CodeGen for C
Library - libcurl

### PR DESCRIPTION
**Pull request by mohnishdeshpande**
## PR Description

Add codegen for C (libcurl).

## Related Issues

- Closes #138 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
_We encourage you to add relevant test cases._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests have not been included_

### CODE REVIEW

**Comment by ashitaprasad** [comment]
The generated code is not working for any of the cases where URL Params are present. Read and follow the instructions provided here properly - https://github.com/foss42/apidash/discussions/80

**Comment by mohnishdeshpande** [comment]
@ashitaprasad Is the code failing to compile or execute? The code was tested with various inputs, including with URL params. Could you please share the input that is causing this behaviour.

**Comment by ashitaprasad** [comment]
@mohnishdeshpande Run the codes generated for all the tests in your local computer.
Now, create requests in API Dash for these models and send request and gather response.
Now match the two outputs.
In the comment below, mention your findings for all request models mentioned in the tests, i.e, GET 1-12, HEAD 1-2, POST 1-9, PUT 1, PATCH 1 & DELETE 1-2

**Comment by animator** [comment]
Provide all setup & testing instructions to run the generated code on machine locally.

**Comment by mohnishdeshpande** [comment]
@ashitaprasad @animator Apologies, I missed that somehow. Anyway, I fixed it. Please have a look at the attached video recording of the working functionality.
[Screencast from 25-03-24 14:53:37.webm](https://github.com/foss42/apidash/assets/77594965/f1d0e411-cee8-470d-94dd-8e0a694a3ef7)
P.S. make sure to add '-lcurl' flag when compiling the code.

**Comment by animator** [comment]
The generated codes have errors and they have not been manually run and verified.
Take a look at other codegen tests.
Closing this PR.

**Pull request closed without merging**
