### PR TITLE
Refactor Javascript Fetch and add Multipart form tests

### LINKED ISSUE #279: Update test script for js (fetch) codegen
**Tell us about the task you want to perform and are unable to do so because the feature is not available**

New example requests have been added - **POST 4 to POST 9** in [test/request_models.dart](https://github.com/foss42/apidash/blob/main/test/request_models.dart) which tests multipart formdata functionality of the codegens. These request models need to be included in the test script for **js (fetch)** codegen. And the result generated must be verified by running it locally before adding it to the test file as the expected code. 

See example test script for [Python (requests)](https://github.com/foss42/apidash/blob/main/test/codegen/python_requests_codegen_test.dart) which covers all the test cases.

To learn more about codegens check out #80

### PR DESCRIPTION
**Pull request by Tanish2002**
## PR Description

Refactored codegen for javascript fetch (both nodejs and js). Fixed up the broken test cases as well as add new tests cases for POST 4-9

## Related Issues

- Related Issue #293 
- Closes #279 #282 

### Checklist
- [x] I have gone through the [contributing guide](https://github.com/foss42/apidash/blob/main/CONTRIBUTING.md)
- [x] I have run the tests (`flutter test`) and all tests are passing

## Added/updated tests?
- [x] Yes

### CODE REVIEW

**Comment by animator** [comment]
@Tanish2002 I was making a minor fix when I saw that the branch was not updated before sending a pull request.
Kindly sync this branch & make sure future branches are synced with main project when you raise a PR.

Screenshot 2024-03-14 at 3 44 05 PM

**Comment by animator** [comment]
Also, please refer to my latest comment [here](https://github.com/foss42/apidash/issues/293#issuecomment-1997150901)

**Comment by Tanish2002** [comment]
@animator made the required changes as well as synced the branch with upstream

**Comment by animator** [comment]
LGTM 🚀

**Pull request merged**
